### ISSUE TITLE
photos not showing in chrome 46

### ISSUE THREAD

**Issue by jaspercram** [jaspercram/refugee#2]
They do show in safari on my mac.

![screen shot 2015-12-03 at 23 33 55](https://cloud.githubusercontent.com/assets/2340870/11576357/5a9f1338-9a16-11e5-9dad-69ac5fb6b851.png)

**Comment by jaspercram** [comment]
Dat was het (uiteraard) niet. Laat ik het toch maar aan de expert over.....

**Comment by maaike** [comment]
Het was de addblocker, yay!
